Specified Platform in Dockerfile

diff --git a/cctl-container/Dockerfile b/cctl-container/Dockerfile
--- a/cctl-container/Dockerfile
+++ b/cctl-container/Dockerfile
@@ -1,11 +1,11 @@
-FROM rust:buster as builder
+FROM --platform=linux/amd64 rust:buster as builder
 
 WORKDIR /usr/src/myapp
 
-COPY /api/src ./src
-COPY api/Cargo.toml  ./
+COPY api/src ./src
+COPY api/Cargo.toml ./
 
-RUN cargo build --release
+RUN cargo build --release || { echo "Compilation failed"; exit 1; }
 
 FROM commondrum/cctl-container:latest
 
@@ -13,7 +13,8 @@ WORKDIR /usr/local/bin
 
 COPY --from=builder /usr/src/myapp/target/release/api ./
 
-
 ENTRYPOINT ["./api"]
 
-EXPOSE 8080
+EXPOSE 3001
+
+CMD ["tail", "-f", "/dev/null"]
